
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
            IRIS_USERNAME: superuser
            IRIS_PASSWORD: SYS
    hostname: NEHRDemo
    container_name: NEHRDemo
    ports: 
      - 1980:1972
      - 52880:52773
